### ISSUE TITLE
墙内访问更新不方便，可否提供墙内镜像？

### ISSUE THREAD

**Issue by nanbowaner** [VeleSila/yhosts#1]
RT

**Comment by VeleSila** [comment]
因为我在墙外，墙内再开一个镜像维护起来太耗时间。

墙内做一个镜像还可能还会涉及到可能会查水表的问题。毕竟Hosts通用性比Adblock强多了。

综上所述，暂时不考虑做镜像。

**Comment by AnyWAT** [comment]
> 墙内访问更新不方便

如用 Hozz 管理更新，（原）项目地址或需代理才正常了。

**Comment by VeleSila** [comment]
我甚至不知道Hozz是什么。。

**Comment by AnyWAT** [comment]
ppoffice/Hozz: [Development indefinitely suspended] A better way to manage your hosts. - https://github.com/ppoffice/Hozz on @github

**Comment by wuhang2003** [comment]
> 因为我在墙外，墙内再开一个镜像维护起来太耗时间。
> 
> 墙内做一个镜像还可能还会涉及到可能会查水表的问题。毕竟hosts通用性比Adblock强多了。
> 
> 综上所述，暂时不考虑做镜像。
> 
> 感谢您的建议。

整 jsDelier 啊，可以引用 Github 上的源文件。

**Comment by AnyWAT** [comment]
#version=2020010251818 有点雷人，以为2020年1月2日。。。

**Comment by VeleSila** [comment]
> 
> 
> > 因为我在墙外，墙内再开一个镜像维护起来太耗时间。
> > 墙内做一个镜像还可能还会涉及到可能会查水表的问题。毕竟hosts通用性比Adblock强多了。
> > 综上所述，暂时不考虑做镜像。
> > 感谢您的建议。
> 
> 整 jsDelivr 啊，可以引用 Github 上的源文件。

惭愧.不会整.

**Comment by VeleSila** [comment]
> 
> 
> #version=2020010251818 有点雷人，以为2020年1月2日。。。

已修复.感谢提醒.

**Comment by icyomik** [comment]
使用CDN加速就可以了，你查下jsdelivr用法：
https://cdn.jsdelivr.net/gh/VeleSila/yhosts/hosts.txt

**Comment by VeleSila** [comment]
> 使用CDN加速就可以了，你查下jsdelivr用法： https://cdn.jsdelivr.net/gh/VeleSila/yhosts/hosts.txt

我不是程序员.最近也比较忙,更新都变慢了.实在是心有余而力不足 -0-
