### ISSUE TITLE
IT之家首页底部弹出的广告条能否过滤。。。

### ISSUE THREAD

**Issue by drw2005** [VeleSila/yhosts#13]
地址：
https://m.ithome.com
感谢！

**Comment by VeleSila** [comment]
![image](https://user-images.githubusercontent.com/8890401/95153359-1bc50780-0744-11eb-8b00-926b38579cc9.png)
你说的是这个图么?

**Comment by drw2005** [comment]
> ![image](https://user-images.githubusercontent.com/8890401/95153359-1bc50780-0744-11eb-8b00-926b38579cc9.png)
> 你说的是这个图么?

是的，就是这个。

**Comment by VeleSila** [comment]
这个是在正常域名下的图片.无法通过hosts屏蔽.
