### ISSUE TITLE
申请网页广告过滤

### ISSUE THREAD

**Issue by drw2005** [VeleSila/yhosts#14]
片库 - 全网高清影视聚合下载
https://www.pianku.li/

见截图：
https://cdn.longdoer.com/2020/12/08/webwxgetmsgimg1c654a97384a82291.jpg
https://cdn.longdoer.com/2020/12/08/webwxgetmsgimgda35686b2d5fa03d.jpg

谢谢！

**Comment by VeleSila** [comment]
不好意思.来晚了.截图已经不可用.

用手机浏览器打开 www.pianku.li 好像并没有看到广告.如果还是有广告麻烦你再提供一下截图.

如果2周内收不到回复,我会关闭这个issue.

**Comment by drw2005** [comment]
手机上是这个地址：https://m.pianku.li/
![logo](https://s3.ax1x.com/2021/01/11/s1XO8P.jpg)

**Comment by VeleSila** [comment]
新版本加入了
ad.xn--3bs795g.link
理论上可以解决. 如果解决不了请反馈. 暂时不关闭这个issue.

Q群好像没收到新的加入申请,我也只是管理员之一.其实Q群我可能会错过,这里就肯定不会.

**Comment by drw2005** [comment]
> 新版本加入了
> ad.xn--3bs795g.link
> 理论上可以解决. 如果解决不了请反馈. 暂时不关闭这个issue.
> 
> Q群好像没收到新的加入申请,我也只是管理员之一.其实Q群我可能会错过,这里就肯定不会.

这两天测试了下，完美屏蔽广告，谢谢！

**Comment by drw2005** [comment]
今天再申请一个：

樱花动漫：http://m.yhdm.io/
二级页面有色情广告

见图：
http://i2.tiimg.com/588674/5c082c632b0faf9f.jpg

谢谢！

**Comment by VeleSila** [comment]
屏蔽以下域名可以解决. 下次更新会加入.你也可以自己手动加入.
p1.pstatp.com
p2.pstatp.com
p3.pstatp.com
p4.pstatp.com
p5.pstatp.com
p6.pstatp.com
p7.pstatp.com
p8.pstatp.com
p9.pstatp.com
p10.pstatp.com
pb1.pstatp.com
pb2.pstatp.com
lq0s3c.cn
vteyf2.cn

下次更新的时候再关闭这个评论.如果又其他网站麻烦你重新开一个issue.感谢支持.
