### ISSUE TITLE
人人影视客户端跟踪器

### ISSUE THREAD

**Issue by groundcat** [VeleSila/yhosts#15]
域名:
tracker1.zmzfile.com
tracker2.zmzfile.com
tracker3.zmzfile.com
tracker4.zmzfile.com
tracker5.zmzfile.com

htracker1.zmzfile.com
htracker2.zmzfile.com
htracker3.zmzfile.com
htracker4.zmzfile.com
htracker5.zmzfile.com

file.apicvn.com

出现场景：
人人影视客户端 3.2.7(1022)

补充说明：
- 经测试，屏蔽上述域名后，不影响客户端正常使用。

**Comment by VeleSila** [comment]
下次更新加入. 加入后会关闭这个issue

感谢反馈.

**Comment by VeleSila** [comment]
已加入.
