### ISSUE TITLE
最近发现今日头条APP的图片加载和评论区打开很慢。。。

### ISSUE THREAD

**Issue by drw2005** [VeleSila/yhosts#16]
有时图片加载需要很长时间，尤其是下面的评论区内容，有时根本加载不出来，有时需要很长时间都能出来。
以前都是瞬间出现的，感觉和咱们的HOSTS有关。
老大看看是哪里的问题。

PS：咱们这个HOSTS我是直接部署在软路由上的。

**Comment by VeleSila** [comment]
因为我没用今日头条,就不太好测试..

暂时只能留着这个issue等更多反馈

**Comment by milestone702** [comment]
p1.pstatp.com这一系列导致头条的文章封面图片被干掉了……

**Comment by VeleSila** [comment]
> 
> 
> p1.pstatp.com这一系列导致头条的文章封面图片被干掉了……

OK. 今天的更新会先屏蔽掉这一系列. 感谢反馈.

**Comment by drw2005** [comment]
这几天使用，好像还是会出现加载很慢的情况。

**Comment by VeleSila** [comment]
没头绪解决缓慢问题.这个Issue关闭归档.
