### ISSUE TITLE
有没有不用挂代理就可以更新的链接？

### ISSUE THREAD

**Issue by drw2005** [VeleSila/yhosts#17]
咱们这个HOSTS在国内需要挂代理更新，想请问有没有不用代理直接更新的方式或者链接？

**Comment by AnyWAT** [comment]
用 https://github.com/ppoffice/Hozz 管理（多个）Hosts 不用代理

**Comment by VeleSila** [comment]
之前有人试过国内的托管,类似gitee这类,自用的.直接被删库了.
所以目前来看是没有.

**Comment by VeleSila** [comment]
> 
> 
> 用 https://github.com/ppoffice/Hozz 管理（多个）Hosts 不用代理

如果是同时管理多个Hosts的话,目前还活着的项目是SwithHosts! 它开源,而且还跨平台.

**Comment by drw2005** [comment]
> > 用 https://github.com/ppoffice/Hozz 管理（多个）Hosts 不用代理
> 
> 如果是同时管理多个Hosts的话,目前还活着的项目是SwithHosts! 它就在Github上开源,而且还跨平台.
我在PC端用的就是SwithHosts!，直接更新咱们的HOSTS不行，我已和SwithHosts!作者反馈增加代理功能了。

**Comment by AnyWAT** [comment]
每次启动Hozz 时才自动更新
![image](https://user-images.githubusercontent.com/37962734/109633528-2664bb00-7b83-11eb-83ed-1273a567b205.png)

**Comment by icyomik** [comment]
https://cdn.jsdelivr.net/gh/VeleSila/yhosts/hosts.txt
