### ISSUE TITLE
有15行重复行哟

### ISSUE THREAD

**Issue by BWZS** [VeleSila/yhosts#18]
文本编辑器去重发现的，emeditor

**Comment by VeleSila** [comment]
能不能麻烦你列出来?
查找无效和重复的工具正在开发/更新中,我暂时没法处理.

**Comment by BWZS** [comment]
127.0.0.1 at.umeng.com
127.0.0.1 e.ac56.xyz
127.0.0.1 e.sxhwscj.cn
127.0.0.1 ee.45xa.cn
127.0.0.1 ee.grtnahd.cn
127.0.0.1 ee.xfya3.cn
127.0.0.1 ib.adnxs.com
127.0.0.1 jscode.jbzj.com
127.0.0.1 m.45xa.cn
127.0.0.1 m.grtnahd.cn
127.0.0.1 m.xfya3.cn
127.0.0.1 pc.weizhenwx.com
127.0.0.1 t.quandangdang.net
127.0.0.1 v.heygugu.com
127.0.0.1 voq3450129.y4j32.cn

**Comment by BWZS** [comment]
> 能不能麻烦你列出来？
> 寻找无效和重复的工具正在开发/更新中，我暂时没法处理。
楼下已列出来了

**Comment by VeleSila** [comment]
> 
> 
> 127.0.0.1 at.umeng.com
> 127.0.0.1 e.ac56.xyz
> 127.0.0.1 e.sxhwscj.cn
> 127.0.0.1 ee.45xa.cn
> 127.0.0.1 ee.grtnahd.cn
> 127.0.0.1 ee.xfya3.cn
> 127.0.0.1 ib.adnxs.com
> 127.0.0.1 jscode.jbzj.com
> 127.0.0.1 m.45xa.cn
> 127.0.0.1 m.grtnahd.cn
> 127.0.0.1 m.xfya3.cn
> 127.0.0.1 pc.weizhenwx.com
> 127.0.0.1 t.quandangdang.net
> 127.0.0.1 v.heygugu.com
> 127.0.0.1 voq3450129.y4j32.cn

下次更新会剔除重复项.届时会关闭着这个issue.

**Comment by VeleSila** [comment]
去重结束.1周后没其它问题就关闭这个issue.

**Comment by BWZS** [comment]
> 去重结束.1周后没其他问题就关闭这个问题。

有仨重复
www.kldsam.com
v.qhruisen.cn
e.sxhwscj.cn

**Comment by BWZS** [comment]
> 去重结束.1周后没其它问题就关闭这个issue.

lp7n.cy6px.com
这行前面有一个空格

**Comment by VeleSila** [comment]
6/17 已解决. 如无新问题,1周后关闭.

**Comment by BWZS** [comment]
> 6/17 已解决. 如无新问题,1周后关闭.

重复项仨
stat.pandora.xiaomi.com
api-access.pangolin-sdk-toutiao.com
ad.mi.com

**Comment by BWZS** [comment]
> 6/17 已解决. 如无新问题,1周后关闭.

误伤s3.pstatp.com，导致樱花动漫pc网页端看不了动漫了

**Comment by VeleSila** [comment]
新版已解决

**Comment by BWZS** [comment]
> 新版已解决

哇，新版本连来源网站都标了。
有四条重复规则
127.0.0.1 ads.static.madserving.com
127.0.0.1 fun.adx.admaster.com.cn
127.0.0.1 a-stage2.tribalfusion.com
127.0.0.1 raddus.bayescom.com

**Comment by BWZS** [comment]
> 新版已解决

还有一个
172.0.0.1 dat1.jzjxmj.com
应该是127.0.0.1吧

**Comment by shuax** [comment]
`0.0.0.0 cdnimg.liehu.ijinshan.com`
重复

**Comment by VeleSila** [comment]
> 
> 
> `0.0.0.0 cdnimg.liehu.ijinshan.com` 重复

解决
