### ISSUE TITLE
建议hosts.txt也加入version

### ISSUE THREAD

**Issue by Beginner-Go** [VeleSila/yhosts#19]
建议hosts.txt加入版本日期

**Comment by Beginner-Go** [comment]
![bate](https://user-images.githubusercontent.com/70857188/109700232-7a47c200-7bcc-11eb-8712-fee0197f5eb0.png)
希望是版本号前  加个空格  这种格式

**Comment by drw2005** [comment]
> 建议hosts.txt加入版本日期

这个建议好，支持一下。

**Comment by VeleSila** [comment]
这次加入.
