### ISSUE TITLE
申请广告过滤

### ISSUE THREAD

**Issue by drw2005** [VeleSila/yhosts#20]
片库网：
http://m.mypianku.com
http://www.pianku.la
https://m.pianku.li/
每页下面都有广告

片源网：
http://pianyuan.tv/
http://pianyuan.la/
上方有广告

前端影视：
https://ddrk.me/

**Comment by VeleSila** [comment]
片库网已解决.这次会更新.
其中http://m.mypianku.com/ 和 https://m.pianku.li/ 都会指向https://m.mypianku.net/

片源网我打不开.可能和我在国外有关系. 我目前没有翻墙回国的渠道.

前端影视的那些图片和JavaScript全部来自ddrk.me的域名,没办法屏蔽.这就是Hosts去广告的局限性.
