### ISSUE TITLE
最近小米电视广告偶尔出现拦不住的情况。。。

### ISSUE THREAD

**Issue by drw2005** [VeleSila/yhosts#22]
近一段时间，偶尔开机居然会出现十几秒的倒数广告。
没发现出现的规律，不知道最近可有人有过这种情况？

**Comment by VeleSila** [comment]
6/17 加入了几个新的小米相关域名.

手头有
f1.market.xiaomi.com
f2.market.xiaomi.com
f3.market.xiaomi.com
f4.market.xiaomi.com
f5.market.xiaomi.com
f1.market.mi-img.com
f2.market.mi-img.com
f3.market.mi-img.com
f4.market.mi-img.com
f5.market.mi-img.com
t1.a.market.xiaomi.com
t2.a.market.xiaomi.com
t3.a.market.xiaomi.com
t4.a.market.xiaomi.com
t5.a.market.xiaomi.com
staging.ai.api.xiaomi.com
stat.pandora.xiaomi.com
de.pandora.xiaomi.com
mishop.pandora.xiaomi.com
