### ISSUE TITLE
请求新增屏蔽：勾正数据（智能电视监视上报所有连网设备）

### ISSUE THREAD

**Issue by groundcat** [VeleSila/yhosts#23]
域名: 
gz-data.com
gzads.com
gozendata.com

出现场景：创维智能电视 勾正数据服务

补充说明：
抓包记录见以下V2EX帖子《我家电视机正在监视所有连网设备》https://www.v2ex.com/t/772523
备份：https://web.archive.org/web/*/https://www.v2ex.com/t/772523

**Comment by VeleSila** [comment]
最早好像是青云瞬月反馈的.
6/17 已加入.  Thank you all the same.
