### ISSUE TITLE
广告数据完善

### ISSUE THREAD

**Issue by vokins** [VeleSila/yhosts#26]
ios游戏的广告数据：
127.0.0.1 api-access.pangolin-sdk-toutiao.com
127.0.0.1 ether-pack.pangolin-sdk-toutiao.com
127.0.0.1 log-api.pangolin-sdk-toutiao.com
127.0.0.1 p1-be-endcard.pglstatp-toutiao.com
127.0.0.1 sf3-be-pack.pglstatp-toutiao.com
127.0.0.1 sf3-fe-tos.pglstatp-toutiao.com
127.0.0.1 sf6-be-pack.pglstatp-toutiao.com
127.0.0.1 v3-be-pack.pglstatp-toutiao.com
127.0.0.1 v6-be-pack.pglstatp-toutiao.com

**Comment by vokins** [comment]
其他游戏广告数据：
127.0.0.1 ms.applovin.com
127.0.0.1 prod-a.applovin.com
127.0.0.1 prod-bid.applovin.com
127.0.0.1 res1.applovin.com
127.0.0.1 aa.toponad.com
127.0.0.1 bds.snssdk.com
127.0.0.1 da.anythinktech.com
127.0.0.1 imp-toutiao-data.37.com.cn
127.0.0.1 impression.appsflyer.com
127.0.0.1 ios.bugly.qq.com
127.0.0.1 is.snssdk.com
127.0.0.1 isub.snssdk.com
127.0.0.1 s3.pstatp.com
127.0.0.1 sf3-ttcdn-tos.pstatp.com
127.0.0.1 smr.snssdk.com
127.0.0.1 tk.anythinktech.com
127.0.0.1 track.tenjin.com
127.0.0.1 ulogs.umeng.com
127.0.0.1 www.tinytapgame.com

**Comment by VeleSila** [comment]
6/17 加入.
辛苦了.
