### ISSUE TITLE
Possible to Remove Some Biased Entries?

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#27]
Could you remove some of the 'hated'-based entries from the list?

https://github.com/vokins/yhosts/blob/9a591b589418bb0674dfe6d82688a70fb1705e52/data/moot/hate.txt

127.0.0.1 acc.maimai.cn
127.0.0.1 apk-ssl.tancdn.com
127.0.0.1 lp.tantanapp.com
127.0.0.1 m.hao123.com
127.0.0.1 maimai.cn
127.0.0.1 s.tantanapp.com
127.0.0.1 shankejingling.com
127.0.0.1 tantanapp.com
127.0.0.1 www.2345.com
127.0.0.1 www.aihuishou.com
127.0.0.1 www.baihe.com
127.0.0.1 www.gome.com.cn
127.0.0.1 www.haier.com
127.0.0.1 www.hao123.com
127.0.0.1 www.hisense.cn
127.0.0.1 www.hisense.com
127.0.0.1 www.jiayuan.com
127.0.0.1 www.yhd.com
127.0.0.1 www.zhongmin.cn
127.0.0.1 yhd.com

**Comment by VeleSila** [comment]
These were originally added by Vokins. Some of them may be widely known/used. However, I do know some of them have bad reputation in advertisement and tracking data. Thus, I would like to respect Vokins's decision.

**Comment by sr093906** [comment]
@VeleSila None of the domains above are ad/tracking domains themselves. They are added just because the original maintainer has unhappy experience with them. 

https://github.com/vokins/yhosts/commit/fe9cad11d20008971beb896945bc6af643d7a99d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by VeleSila** [comment]
As you can see in the link you provided and the readme in this folk, this hosts file is "主观且不好用", which means subjective and not handy. I do have unpleasant experience with at least some of them. Thus, I would respect Vokins's decision.

**Comment by sr093906** [comment]
Thanks for reminding. This really gives me a lesson. Next time, I will not do such silly thing to file a issue with a ' subjective and not handy' repo. I will just fork it. 🤣
