### ISSUE TITLE
開設telegram群組

### ISSUE THREAD

**Issue by c2xusnpq6** [VeleSila/yhosts#28]
這個廣告黑名單repo也有開 您可以參考一下

https://github.com/banbendalao/ADgk

> 反馈交流群
QQ群①:875865300
QQ群②:723295076
TG群:https://t.me/ADgk_list

**Comment by VeleSila** [comment]
因为还要研究协议的原因,还有精力也有限.我一般就不会去投入时间去研究别人的名单了.不过依旧感谢你的热心提供信息.
