### ISSUE TITLE
Additions to Taboola 

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#29]
127.0.0.1 ads.taboola.com
127.0.0.1 am-trc-events.taboola.com
127.0.0.1 am-trc-f.taboola.com
127.0.0.1 am-vid-events.taboola.com
127.0.0.1 beacon.taboola.com
127.0.0.1 ch-match.taboola.com
127.0.0.1 ch-trc.taboola.com
127.0.0.1 ch-trc-events.taboola.com
127.0.0.1 ch-vid-events.taboola.com
127.0.0.1 clickam.taboola.com
127.0.0.1 clickch.taboola.com
127.0.0.1 clickhk.taboola.com
127.0.0.1 clicknj.taboola.com
127.0.0.1 clickus.taboola.com
127.0.0.1 cn-test.taboola.com
127.0.0.1 cn-trc.taboola.com
127.0.0.1 hk-match.taboola.com
127.0.0.1 hk-trc.taboola.com
127.0.0.1 hk-trc-events.taboola.com
127.0.0.1 hk-trc-f.taboola.com
127.0.0.1 hk-vid-events.taboola.com
127.0.0.1 il-trc.taboola.com
127.0.0.1 il-trc-events.taboola.com
127.0.0.1 nr-events.taboola.com
127.0.0.1 popup.taboola.com
127.0.0.1 pvc.taboola.com
127.0.0.1 sg-trc-events.taboola.com
127.0.0.1 sg-vid-events.taboola.com
127.0.0.1 static.taboola.com
127.0.0.1 tracker.taboola.com
127.0.0.1 tracking.taboola.com
127.0.0.1 trc0.taboola.com
127.0.0.1 trc-china.taboola.com
127.0.0.1 trc-events.taboola.com
127.0.0.1 trctest.taboola.com
127.0.0.1 trc-tls13.taboola.com
127.0.0.1 trc-yjp.taboola.com
127.0.0.1 trk.taboola.com
127.0.0.1 us-match.taboola.com
127.0.0.1 us-trc.taboola.com
127.0.0.1 us-trc-events.taboola.com
127.0.0.1 us-trc-f.taboola.com
127.0.0.1 us-vid-events.taboola.com
127.0.0.1 vidanalytics.taboola.com

**Comment by VeleSila** [comment]
感谢反馈.下个更新会加入.
