### ISSUE TITLE
whitelist -> get3.adobe.com

### ISSUE THREAD

**Issue by scafroglia93** [VeleSila/yhosts#3]
Reference ->
https://github.com/nextdns/metadata/issues/188

**Comment by scafroglia93** [comment]
can you give me the exact link for vokins list please ?

**Comment by scafroglia93** [comment]
wait for your info

**Comment by scafroglia93** [comment]
127.0.0.1 get3.adobe.com

**Comment by VeleSila** [comment]
It was block for a specific purpose. I'm not an expert on that topic and I don't want to remove it at this point.

Thank you for your feedback.
