### ISSUE TITLE
Additions to Mediav

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#30]
127.0.0.1 ad-test.mediav.com
127.0.0.1 dsp-lb.mediav.com
127.0.0.1 gdt.dsp.mediav.com
127.0.0.1 jupin.mediav.com
127.0.0.1 munion.mediav.com
127.0.0.1 static.i.mediav.com
127.0.0.1 static.ju.mediav.com
127.0.0.1 static.jupin.mediav.com
127.0.0.1 360.munion.mediav.com

**Comment by VeleSila** [comment]
Thank you. It will be included in coming update.
