### ISSUE TITLE
Additions to Admaster

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#31]
127.0.0.1 25c8e.admaster.com.cn
127.0.0.1 7r29uu.vyk.admaster.com.cn
127.0.0.1 7r3cna.viqiyi.admaster.com.cn
127.0.0.1 7r76oa.vyk.admaster.com.cn
127.0.0.1 7r8a9a.viqiyi.admaster.com.cn
127.0.0.1 8b253a.vyk.admaster.com.cn
127.0.0.1 8b26nu.viqiyi.admaster.com.cn
127.0.0.1 8b6fqu.vyk.admaster.com.cn
127.0.0.1 8b6fxa.viqiyi.admaster.com.cn
127.0.0.1 8b8a4a.viqiyi.admaster.com.cn
127.0.0.1 8b8a6a.vsohu.admaster.com.cn
127.0.0.1 8b8a7u.vyk.admaster.com.cn
127.0.0.1 8c8vqu.vyk.admaster.com.cn
127.0.0.1 8cayca.viqiyi.admaster.com.cn
127.0.0.1 8cayga.vsohu.admaster.com.cn
127.0.0.1 8cbbwu.vsohu.admaster.com.cn
127.0.0.1 8cc6au.viqiyi.admaster.com.cn
127.0.0.1 8cc6bu.viqiyi.admaster.com.cn
127.0.0.1 8ccxfa.viqiyi.admaster.com.cn
127.0.0.1 8cd9gu.viqiyi.admaster.com.cn
127.0.0.1 8ce0zu.viqiyi.admaster.com.cn
127.0.0.1 8ceivu.vsohu.admaster.com.cn
127.0.0.1 8cf27a.viqiyi.admaster.com.cn
127.0.0.1 8cf3ha.vsohu.admaster.com.cn
127.0.0.1 8cffau.viqiyi.admaster.com.cn
127.0.0.1 8cgzvu.viqiyi.admaster.com.cn
127.0.0.1 8ci19u.vyk.admaster.com.cn
127.0.0.1 8ci2nu.vyk.admaster.com.cn
127.0.0.1 8ci46u.vyk.admaster.com.cn
127.0.0.1 8cifgu.vyk.admaster.com.cn
127.0.0.1 8cnvwu.viqiyi.admaster.com.cn
127.0.0.1 8csbxu.vsohu.admaster.com.cn
127.0.0.1 8csexa.vfs.admaster.com.cn
127.0.0.1 8dcn5u.viqiyi.admaster.com.cn
127.0.0.1 8dqc4u.viqiyi.admaster.com.cn
127.0.0.1 8dvzfa.vfs.admaster.com.cn
127.0.0.1 azarlive-branch.vsohu.admaster.com.cn
127.0.0.1 banner.as.admaster.com.cn
127.0.0.1 banneras.admaster.com.cn
127.0.0.1 coocaa.admaster.com.cn
127.0.0.1 fun.adx.admaster.com.cn
127.0.0.1 hdt.adx.admaster.com.cn
127.0.0.1 i18q.admaster.com.cn
127.0.0.1 jice.admaster.com.cn
127.0.0.1 kz.admaster.com.cn
127.0.0.1 mma.admaster.com.cn
127.0.0.1 mms2017.admaster.com.cn
127.0.0.1 open.admaster.com.cn
127.0.0.1 p.admaster.com.cn
127.0.0.1 survey.admaster.com.cn
127.0.0.1 tag.admaster.com.cn
127.0.0.1 track-help.admaster.com.cn
127.0.0.1 track.admaster.com.cn
127.0.0.1 ty.viqiyi.admaster.com.cn
127.0.0.1 ty.vletv.admaster.com.cn
127.0.0.1 vfs.admaster.com.cn
127.0.0.1 vspa.admaster.com.cn
127.0.0.1 vtyqy.admaster.com.cn
127.0.0.1 www.vyk.admaster.com.cn

**Comment by VeleSila** [comment]
Thank you. It will be included in coming update.
