### ISSUE TITLE
Additions to Applovin

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#36]
127.0.0.1 albtest.applovin.com
127.0.0.1 a-support.applovin.com
127.0.0.1 data.applovin.com
127.0.0.1 dev-www.applovin.com
127.0.0.1 growth-support.applovin.com
127.0.0.1 ms-d.applovin.com
127.0.0.1 nuqstage-msevent.applovin.com
127.0.0.1 nyjprod-msevent.applovin.com
127.0.0.1 nyjstage-msevent.applovin.com
127.0.0.1 prod-a4.applovin.com
127.0.0.1 stage-ms.applovin.com
127.0.0.1 ue.applovin.com
127.0.0.1 zn7zcrzms3zdyzvrobkdqdrphkvijejz-a.applovin.com

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
