### ISSUE TITLE
Additions to exoclick

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#37]
127.0.0.1 syndication-evo.exoclick.com
127.0.0.1 syndication-whk1.exoclick.com
127.0.0.1 syndication-gceuw1.exoclick.com
127.0.0.1 origin-static.exoclick.com
127.0.0.1 syndication-adblock.exoclick.com
127.0.0.1 syndication0.exoclick.com
127.0.0.1 syndication-p.exoclick.com
127.0.0.1 logs.exoclick.com
127.0.0.1 static0.exoclick.com
127.0.0.1 cs-stats0.exoclick.com

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
