### ISSUE TITLE
Additions to Youmi

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#38]
127.0.0.1 ad1.img.static.youmi.net
127.0.0.1 ad2.img.static.youmi.net
127.0.0.1 adchn.youmi.net
127.0.0.1 analytics.youmi.net
127.0.0.1 app-facade.youmi.net
127.0.0.1 dev.youmi.net
127.0.0.1 f8d.stat.gw.youmi.net
127.0.0.1 feedback.youmi.net
127.0.0.1 pop.youmi.net
127.0.0.1 stat-wsa.gw.youmi.net
127.0.0.1 wall.static.youmi.net

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
