### ISSUE TITLE
Additions to oadz

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#39]
127.0.0.1 a1.oadz.com
127.0.0.1 a1015.oadz.com
127.0.0.1 a1480.oadz.com
127.0.0.1 a1514.oadz.com
127.0.0.1 a1761.oadz.com
127.0.0.1 a1872.oadz.com
127.0.0.1 a2061.oadz.com
127.0.0.1 a2430.oadz.com
127.0.0.1 a2709.oadz.com
127.0.0.1 app.oadz.com
127.0.0.1 dev.oadz.com
127.0.0.1 dm.oadz.com
127.0.0.1 dsp.oadz.com
127.0.0.1 fac2.oadz.com
127.0.0.1 push.oadz.com
127.0.0.1 s.oadz.com

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
