### ISSUE TITLE
Additions to Tanx

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#40]
127.0.0.1 ade.tanx.com
127.0.0.1 adx.tanx.com
127.0.0.1 click.gds.tanx.com
127.0.0.1 na61-na62-eu95.wagbridge.advertisement.tanx.com
127.0.0.1 na61-na62-st3.wagbridge.advertisement.tanx.com
127.0.0.1 na61-na62.wagbridge.advertisement.tanx.com
127.0.0.1 ot7.wagbridge.advertisement.tanx.com
127.0.0.1 secgw-na61-na62.wagbridge.advertisement.tanx.com
127.0.0.1 st3.wagbridge.advertisement.tanx.com
127.0.0.1 itemifs.tanx.com
127.0.0.1 kgb-ifs.tanx.com
127.0.0.1 ifsk2.tanx.com
127.0.0.1 xifs.tanx.com
127.0.0.1 toruk.gds.tanx.com
127.0.0.1 live-ifs.tanx.com
127.0.0.1 ssp.tanx.com

I am 'conservative' when adding new entries. Actually, there are hundreds of subdomains available to add based on
https://etip.exodus-privacy.eu.org/trackers/7c094493-ee4f-4f11-955a-7ff2b6c6a521/

**Comment by VeleSila** [comment]
"Conservative" is a good thing for this list. lol

Thank you. Will be included in coming update.
