### ISSUE TITLE
Additions to vlion

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#42]
127.0.0.1 u.vlion.cn		
127.0.0.1 jira.vlion.cn
127.0.0.1 dsp.vlion.cn
127.0.0.1 rta.vlion.cn
127.0.0.1 dmp.vlion.cn
127.0.0.1 v.vlion.cn
127.0.0.1 c.vlion.cn
127.0.0.1 n.vlion.cn
127.0.0.1 a-bj.vlion.cn
127.0.0.1 q.vlion.cn
127.0.0.1 hippo.vlion.cn
127.0.0.1 b.vlion.cn
127.0.0.1 mammut.vlion.cn
127.0.0.1 test.vlion.cn
127.0.0.1 g.vlion.cn
127.0.0.1 tophippo.vlion.cn

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
