### ISSUE TITLE
Additions to mmstat

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#44]
127.0.0.1 log.mmstat.com
127.0.0.1 log7.mmstat.com
127.0.0.1 cctv.mmstat.com
127.0.0.1 perf.mmstat.com
127.0.0.1 log.gds.mmstat.com
127.0.0.1 log5.mmstat.com
127.0.0.1 log1.mmstat.com
127.0.0.1 perf.gds.mmstat.com

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
