### ISSUE TITLE
Additions to Alimama

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#45]
127.0.0.1 ad.alimama.com
127.0.0.1 c.click.alimama.com
127.0.0.1 adsh.wagbridge.taobao.alimama.com
127.0.0.1 adsh.wagbridge.tmall.alimama.com
127.0.0.1 adsz.wagbridge.taobao.alimama.com
127.0.0.1 ad-sh-sz-zb.wagbridge.tanx.alimama.com
127.0.0.1 adsh.wagbridge.1688.alimama.com
127.0.0.1 pre3-ad.alimama.com
127.0.0.1 adsz.wagbridge.1688.alimama.com
127.0.0.1 pre-ad.alimama.com
127.0.0.1 pre-adv.alimama.com
127.0.0.1 adsz.wagbridge.tanx.alimama.com
127.0.0.1 adsh.wagbridge.alibaba.alimama.com
127.0.0.1 adx.alimama.com
127.0.0.1 adsh.wagbridge.tanx.alimama.com
127.0.0.1 adsz.wagbridge.tmall.alimama.com
127.0.0.1 pre2-ad.alimama.com
127.0.0.1 tf.logview.alimama.com
127.0.0.1 logview.uc.alimama.com

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
