### ISSUE TITLE
Additions to bayimob

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#47]
127.0.0.1 ios.bayimob.com
127.0.0.1 api.bayimob.com
127.0.0.1 client.bayimob.com	
127.0.0.1 dev.bayimob.com	
127.0.0.1 interaction1.bayimob.com
127.0.0.1 alicdn.bayimob.com		
127.0.0.1 wannianli.bayimob.com

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
