### ISSUE TITLE
Additions to ad-stir.com

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#48]
127.0.0.1 blue-ad.ad-stir.com
127.0.0.1 nad.ad-stir.com
127.0.0.1 js2.ad-stir.com	
127.0.0.1 dl.ad-stir.com		
127.0.0.1 cf-ad.ad-stir.com		
127.0.0.1 stage-uev.ad-stir.com
127.0.0.1 api.ad.ad-stir.com
127.0.0.1 ad.shepard.ad-stir.com
127.0.0.1 click.bpc.ad-stir.com	
127.0.0.1 uev.ad-stir.com	
127.0.0.1 sync.ad-stir.com		
127.0.0.1 click.ad-stir.com
127.0.0.1 mon.ad-stir.com
127.0.0.1 ad-api.ad-stir.com	
127.0.0.1 nad-stage1.ad-stir.com
127.0.0.1 green-ad.ad-stir.com

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
