### ISSUE TITLE
Additions to Bayescom

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#49]
127.0.0.1 blink.bayescom.com
127.0.0.1 raddus.bayescom.com
127.0.0.1 jupiter.bayescom.com
127.0.0.1 jupiter2.bayescom.com
127.0.0.1 api.bayescom.com
127.0.0.1 blink-upload.bayescom.com
127.0.0.1 shuttle.bayescom.com

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
