### ISSUE TITLE
App什么值得买

### ISSUE THREAD

**Issue by myeveryheart** [VeleSila/yhosts#5]
没能屏蔽什么值得买的开屏广告
平台:app
系统:Android
下载地址:任何应用商店

**Comment by VeleSila** [comment]
开屏广告很多因为本身来自正常域名，不能通过hosts屏蔽。我大概知道怎么去查开屏广告，但是因为大概率不会有收获（原因来自第一句），而且这个app我也没装。。
如果你能提供应该拦截的域名并测试成功，我会加入进去。
感谢热心反馈。
