### ISSUE TITLE
Additions to cacafly

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#50]
127.0.0.1 mrbs.cacafly.com
127.0.0.1 rp3.cacafly.com
127.0.0.1 nativeads.cacafly.com
127.0.0.1 rp.cacafly.com
127.0.0.1 appx.cacafly.com
127.0.0.1 gateway.cacafly.com
127.0.0.1 apps2.cacafly.com
127.0.0.1 lyncdiscover.cacafly.com
127.0.0.1 flarefilter.cacafly.com
127.0.0.1 apps.cacafly.com
127.0.0.1 app.cacafly.com
127.0.0.1 www.flarefilter.cacafly.com

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
