### ISSUE TITLE
Additions to Flurry

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#51]
127.0.0.1 ad-verify.flurry.com
127.0.0.1 ads-verify.flurry.com
127.0.0.1 apac-ads.flurry.com
127.0.0.1 api-metrics-canary.flurry.com
127.0.0.1 api-metrics-e2e.nonprod.flurry.com
127.0.0.1 api-metrics-smoke.nonprod.flurry.com
127.0.0.1 api-metrics.flurry.com
127.0.0.1 api-verify.flurry.com
127.0.0.1 api.flurry.com
127.0.0.1 app.flurry.com
127.0.0.1 data-canary.flurry.com
127.0.0.1 data-ipv6.flurry.com
127.0.0.1 data-k8s.flurry.com
127.0.0.1 data.real.flurry.com
127.0.0.1 geo.flurry.com
127.0.0.1 gw.flurry.com
127.0.0.1 pilot-ad.flurry.com
127.0.0.1 pilot-api.flurry.com
127.0.0.1 pilot-data.flurry.com
127.0.0.1 proton-int.flurry.com
127.0.0.1 pulse.data.flurry.com
127.0.0.1 realtime-metrics.flurry.com
127.0.0.1 staging-ads.flurry.com

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
