### ISSUE TITLE
Additions to hot-mob

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#52]
127.0.0.1 cdn.hot-mob.com
127.0.0.1 track.hot-mob.com
127.0.0.1 wap.hot-mob.com
127.0.0.1 network.hot-mob.com
127.0.0.1 monitor.hot-mob.com
127.0.0.1 dsp.hot-mob.com
127.0.0.1 www3.hot-mob.com
127.0.0.1 trk.hot-mob.com
127.0.0.1 testad.hot-mob.com
127.0.0.1 www2.hot-mob.com
127.0.0.1 webapi.hot-mob.com
127.0.0.1 cors.hot-mob.com
127.0.0.1 adsite.hot-mob.com

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
