### ISSUE TITLE
Additions to leadboltads.net

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#53]
127.0.0.1 ads.leadboltads.net
127.0.0.1 www.ad.leadboltads.net
127.0.0.1 5ad.leadboltads.net
127.0.0.1 ww2.leadboltads.net
127.0.0.1 atlas.leadboltads.net
127.0.0.1 nad.leadboltads.net
127.0.0.1 training.leadboltads.net
127.0.0.1 ww1.leadboltads.net
127.0.0.1 ww4.leadboltads.net
127.0.0.1 ww3.leadboltads.net
127.0.0.1 ad7.leadboltads.net

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
