### ISSUE TITLE
Additions to madserving

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#55]
127.0.0.1 api.dsp.madserving.com
127.0.0.1 aws.dsp.madserving.com
127.0.0.1 ad.beta.madserving.com
127.0.0.1 clk.premium.madserving.com
127.0.0.1 bj.appsrv1.madserving.com
127.0.0.1 advbeta.madserving.com
127.0.0.1 srv.dsp.madserving.com
127.0.0.1 ad.dongdong.madserving.com
127.0.0.1 ad.poco.madserving.com
127.0.0.1 track.madserving.com
127.0.0.1 cntrack.madserving.com
127.0.0.1 clkpremium.madserving.com
127.0.0.1 ads.static.madserving.com

**Comment by VeleSila** [comment]
Thank you.
Will be included in coming update.
