### ISSUE TITLE
Additions to propellerads

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#56]
127.0.0.1 geoip.propellerads.com
127.0.0.1 cdn.propellerads.com
127.0.0.1 log-manager.propellerads.com
127.0.0.1 tracking2.propellerads.com
127.0.0.1 statsv2.propellerads.com
127.0.0.1 apistats.propellerads.com
127.0.0.1 stats.propellerads.com
127.0.0.1 ab-config.propellerads.com
127.0.0.1 report.propellerads.com
127.0.0.1 tracking.propellerads.com
127.0.0.1 apiad.propellerads.com
127.0.0.1 apistats-static.propellerads.com
127.0.0.1 adp.propellerads.com
127.0.0.1 native.propellerads.com

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
