### ISSUE TITLE
Additions to amobee

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#57]
127.0.0.1 beacon2.turn.com
127.0.0.1 static.turn.com
127.0.0.1 api.turn.com
127.0.0.1 metrics.turn.com
127.0.0.1 status.turn.com
127.0.0.1 ak.ad.turn.com
127.0.0.1 d-audienceiq-hkg1.turn.com
127.0.0.1 d-audienceiq-atl1.turn.com
127.0.0.1 beacon1.turn.com
127.0.0.1 console-audienceiq-sjc2.turn.com
127.0.0.1 ad2.turn.com
127.0.0.1 ad2.cdns.turn.com
127.0.0.1 attadworks.turn.com
127.0.0.1 www.adworks.att.com.turn.com

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
