### ISSUE TITLE
Additions to nend

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#59]
127.0.0.1 impression.nend.net
127.0.0.1 ymurase.ad.dev.nend.net
127.0.0.1 m-hayakawa.ad.dev.nend.net
127.0.0.1 yamada2-dev.nend.net
127.0.0.1 ad3.nend.net
127.0.0.1 rtb.tamura.ad.dev.nend.net
127.0.0.1 hsts.rtb.tamura.ad.dev.nend.net
127.0.0.1 yamada.ad.dev.nend.net
127.0.0.1 api.nend.net
127.0.0.1 ad4.nend.net
127.0.0.1 static-interactive-api.nend.net

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
