### ISSUE TITLE
Additions to hinet

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#60]
127.0.0.1 mobileeventad-hamivideo.cdn.hinet.net
127.0.0.1 mobilevodad-hamivideo.cdn.hinet.net
127.0.0.1 cdnonetag-onead.cdn.hinet.net
127.0.0.1 imagead-gtut.cdn.hinet.net
127.0.0.1 mail-ad2.hisys.hinet.net
127.0.0.1 weblivead-hamivideo.cdn.hinet.net
127.0.0.1 ad-adbert.cdn.hinet.net
127.0.0.1 dsp-onead.cdn.hinet.net
127.0.0.1 osm-onead.cdn.hinet.net
127.0.0.1 ad-ettoday.cdn.hinet.net
127.0.0.1 mail-ad3.hisys.hinet.net
127.0.0.1 ndm-onead.cdn.hinet.net
127.0.0.1 cdnonead-onead.cdn.hinet.net
127.0.0.1 mail-ad1.hisys.hinet.net
127.0.0.1 cdnpixel-onead.cdn.hinet.net
127.0.0.1 cdnstaging-onead.cdn.hinet.net
127.0.0.1 wdm-onead.cdn.hinet.net
127.0.0.1 cdncreative-onead.cdn.hinet.net
127.0.0.1 cdnadspecs-onead.cdn.hinet.net
127.0.0.1 odd-onead.cdn.hinet.net
127.0.0.1 osd-onead.cdn.hinet.net
127.0.0.1 odm-onead.cdn.hinet.net
127.0.0.1 wsm-onead.cdn.hinet.net
127.0.0.1 mail-ad4.hisys.hinet.net
127.0.0.1 adv-ettoday.cdn.hinet.net

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
