### ISSUE TITLE
Additions to icast

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#62]
127.0.0.1 ssp.res.icast.cn		
127.0.0.1 rmtxpv.ra.icast.cn	
127.0.0.1 map1dx.ra.icast.cn
127.0.0.1 mapdx.icast.cn	
127.0.0.1 track2.ra.icast.cn	
127.0.0.1 cp.ra.icast.cn	
127.0.0.1 tk.icast.cn
127.0.0.1 s2.ra.icast.cn	
127.0.0.1 app.icast.cn
127.0.0.1 open.icast.cn
127.0.0.1 tx.icast.cn
127.0.0.1 map1.ra.icast.cn	
127.0.0.1 cdn3.icast.cn
127.0.0.1 ssp.icast.cn
127.0.0.1 h2.res.icast.cn
127.0.0.1 mocast.ra.icast.cn

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
