### ISSUE TITLE
Additions to ninebox

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#64]
127.0.0.1 up.ninebox.cn
127.0.0.1 b.ninebox.cn	
127.0.0.1 ifv.ninebox.cn		
127.0.0.1 s.ninebox.cn		
127.0.0.1 pull.ninebox.cn
127.0.0.1 a23.ninebox.cn	
127.0.0.1 c.ninebox.cn	
127.0.0.1 push.ninebox.cn	
127.0.0.1 screenshot.ninebox.cn
127.0.0.1 p.ninebox.cn	
127.0.0.1 img.ninebox.cn
127.0.0.1 e.ninebox.cn

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
