### ISSUE TITLE
Additions to agrantsem

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#65]
127.0.0.1 t.agrantsem.com	
127.0.0.1 adtest.agrantsem.com
127.0.0.1 ad.agrantsem.com	
127.0.0.1 img2.ad.agrantsem.com		
127.0.0.1 uc.agrantsem.com
127.0.0.1 ttt.agrantsem.com
127.0.0.1 dyna.agrantsem.com
127.0.0.1 img3.ad.agrantsem.com		
127.0.0.1 frontstat.agrantsem.com
127.0.0.1 rd.adn.agrantsem.com	
127.0.0.1 tt4.agrantsem.com
127.0.0.1 ceadx.agrantsem.com
127.0.0.1 tt.agrantsem.com
127.0.0.1 api.agrantsem.com	
127.0.0.1 se.api.agrantsem.com
127.0.0.1 www.static.t.agrantsem.com
127.0.0.1 360dianjing.agrantsem.com
127.0.0.1 kd.api.agrantsem.com
127.0.0.1 ttt4.agrantsem.com

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
