### ISSUE TITLE
Additions to advertising.com

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#68]
127.0.0.1 ads-ap.adaptv.advertising.com
127.0.0.1 ads-ec.adaptv.advertising.com
127.0.0.1 ads-eu.adaptv.advertising.com
127.0.0.1 ads-wc.adaptv.advertising.com
127.0.0.1 adserver-as.adtech.advertising.com
127.0.0.1 adserver-eu.adtech.advertising.com
127.0.0.1 adserver-us.adtech.advertising.com
127.0.0.1 adserver.adtech.advertising.com
127.0.0.1 eu.event.cmp.advertising.com
127.0.0.1 guce.advertising.com
127.0.0.1 hb-as.adtech.advertising.com
127.0.0.1 log-nj.adaptv.advertising.com
127.0.0.1 log-sj-eq.adaptv.advertising.com
127.0.0.1 log-sj.adaptv.advertising.com
127.0.0.1 log.adaptv.advertising.com
127.0.0.1 mads.advertising.com
127.0.0.1 mobileapi.advertising.com
127.0.0.1 tag-dev.sp.advertising.com
127.0.0.1 us.event.cmp.advertising.com

**Comment by VeleSila** [comment]
Will be included in coming update.

Thank you.
