### ISSUE TITLE
Additions to adeaz

### ISSUE THREAD

**Issue by sr093906** [VeleSila/yhosts#69]
127.0.0.1 jira.adeaz.com
127.0.0.1 www.adeaz.com
127.0.0.1 hz.adeaz.com
127.0.0.1 newsbee.adeaz.com	
127.0.0.1 touch.adeaz.com	
127.0.0.1 sx.adm.adeaz.com
127.0.0.1 third.adeaz.com		
127.0.0.1 sa.adeaz.com	
127.0.0.1 g.sa.adeaz.com	
127.0.0.1 i.adeaz.com
127.0.0.1 data.adeaz.com	
127.0.0.1 ddy.adeaz.com		
127.0.0.1 wukong.adeaz.com
127.0.0.1 j.adeaz.com	
127.0.0.1 pic.adeaz.com

**Comment by VeleSila** [comment]
Thank you. Will be included in coming update.
