### ISSUE TITLE
Jun 27 22:58:22 dnsmasq[4398]: bad address at /jffs/configs/hosts line 3****

### ISSUE THREAD

**Issue by klcb2010** [VeleSila/yhosts#70]
![QQ截图20210627225944](https://user-images.githubusercontent.com/32628414/123549846-4f960080-d79d-11eb-80b4-5c9ccf1b58cb.png)
![QQ截图20210627225918](https://user-images.githubusercontent.com/32628414/123549858-56bd0e80-d79d-11eb-8d33-24daa7da317b.png)
梅林路由提示这个错误 但是hosts文件好像是正常的，根据这个教程https://www.ibloglife.com/archives/3934.html 做的。

**Comment by klcb2010** [comment]
图片

**Comment by VeleSila** [comment]
我没有用路由器,这方面不太熟悉,看了下提示的那些行,都是接近4万了.yhosts还不到1万行.具体什么原因我也不太了解.
没帮上忙,十分抱歉. 你可以选择去QQ群里请教一下.
