### ISSUE TITLE
add settlef.com

### ISSUE THREAD

**Issue by enihcam** [VeleSila/yhosts#76]

**Comment by VeleSila** [comment]
Are there anything before settlef.com? 

Such as ads.settlef.com

**Comment by VeleSila** [comment]
> _No description provided._

Are there anything before settlef.com?

Such as ads.settlef.com

**Comment by enihcam** [comment]
> > _No description provided._
> 
> Are there anything before settlef.com?
> 
> Such as ads.settlef.com

no.

**Comment by VeleSila** [comment]
Will be added in coming update. This issue will be closed after the update.

Thank you for your input.
